version: "3"

services:
  bot:
    build: ./bot
    container_name: zalupa_bot
    restart: on-failure 
    command: python /app/main.py 
    ports:
       - "5000:5000"
    volumes:
      - ./:/app
      - ./shared_data:/shared_data


  site:
    build: ./site
    container_name: frontend
    restart: on-failure 
    ports:
       - "3000:3000"
    volumes:
      - ./:/app
      - ./shared_data:/shared_data

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/home/web/default/static
      - ./templates:/home/web/default/templates
      - ./shared_data:/shared_data
