#В этом файде будет хранится текст для сообщений
#text_start = "Добрый день {message.from_user.first_name}, это - телеграм бот компании Ростелеком, в нем вы можете проверить возможность до адреса и статус вашей заявки"
text_enter_address = "Введите адрес \n"
text_enter_application = "Введите заявку \n"
text_3 = ""
text_4 = ""
text_5 = ""
text_6= ""
text_7 = ""
text_8 = ""
text_9 = ""
text_10 = ""
text_11 = ""
text_12 = ""
